# Generated by Django 5.2.16 on 2026-08-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
